# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"download_santander_data": "00_data_prep.ipynb",
         "unzip": "00_data_prep.ipynb",
         "SandanderData": "00_data_prep.ipynb"}

modules = ["data.py"]

doc_url = "https://WFR.github.io/community_learning/"

git_url = "https://github.com/WFR/community_learning/tree/master/"

def custom_doc_links(name): return None
