# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"download_santander_data": "01_data_preprocess.ipynb",
         "unzip": "01_data_preprocess.ipynb",
         "timeit": "01_data_preprocess.ipynb",
         "canal_dict": "01_data_preprocess.ipynb",
         "pais_dict": "01_data_preprocess.ipynb",
         "emp_dict": "01_data_preprocess.ipynb",
         "indfall_dict": "01_data_preprocess.ipynb",
         "sexo_dict": "01_data_preprocess.ipynb",
         "tiprel_dict": "01_data_preprocess.ipynb",
         "indresi_dict": "01_data_preprocess.ipynb",
         "indext_dict": "01_data_preprocess.ipynb",
         "conyuemp_dict": "01_data_preprocess.ipynb",
         "segmento_dict": "01_data_preprocess.ipynb",
         "resize_data": "01_data_preprocess.ipynb",
         "preprocess_csv": "01_data_preprocess.ipynb",
         "load_data": "04_base_model.ipynb",
         "clean_age": "02_data_Cleaning.ipynb",
         "clean_renta": "02_data_Cleaning.ipynb",
         "clean_all_data": "02_data_Cleaning.ipynb",
         "target_cols": "04_base_model.ipynb",
         "feature_cols": "04_base_model.ipynb",
         "calculate_targets": "03_features.ipynb",
         "remove_rows_without_product": "03_features.ipynb",
         "calculate_target_as_one_column": "03_features.ipynb",
         "get_last_month_test_set": "03_features.ipynb",
         "get_train_set": "03_features.ipynb",
         "calculate_main": "03_features.ipynb",
         "get_shift_cols": "04_base_model.ipynb",
         "get_product_dict": "04_base_model.ipynb",
         "get_product_reverse_dict": "04_base_model.ipynb",
         "encode_products": "04_base_model.ipynb",
         "x_y_split": "04_base_model.ipynb",
         "runXGB": "04_base_model.ipynb",
         "apk": "04_base_model.ipynb",
         "get_results": "04_base_model.ipynb",
         "get_base_model_results": "04_base_model.ipynb"}

modules = ["preprocess_data.py",
           "data_preparation.py",
           "features.py",
           "base_model.py"]

doc_url = "https://submitCode.github.io/community_learning/"

git_url = "https://github.com/submitCode/community_learning/tree/master/"

def custom_doc_links(name): return None
