# AUTOGENERATED! DO NOT EDIT! File to edit: 03_target_vars.ipynb (unless otherwise specified).

__all__ = ['load_data', 'target_cols', 'calculate_targets']

# Cell
import pandas as pd
import numpy as np

from fastscript import *

# Cell
def load_data(path='data/interim/02_train.csv'):
    """load data"""
    return pd.read_csv(path)

# Cell
target_cols = ['ind_ahor_fin_ult1','ind_aval_fin_ult1','ind_cco_fin_ult1',
               'ind_cder_fin_ult1','ind_cno_fin_ult1','ind_ctju_fin_ult1',
               'ind_ctma_fin_ult1','ind_ctop_fin_ult1','ind_ctpp_fin_ult1',
               'ind_deco_fin_ult1','ind_deme_fin_ult1','ind_dela_fin_ult1',
               'ind_ecue_fin_ult1','ind_fond_fin_ult1','ind_hip_fin_ult1',
               'ind_plan_fin_ult1','ind_pres_fin_ult1','ind_reca_fin_ult1',
               'ind_tjcr_fin_ult1','ind_valo_fin_ult1','ind_viv_fin_ult1',
               'ind_nomina_ult1','ind_nom_pens_ult1','ind_recibo_ult1']

# Cell
def calculate_targets(df:pd.DataFrame, target_products:list=target_cols):
    """add the shifted product values and calculate target variables"""
    df.sort_values(by = ['id', 'month_int'], inplace=True) #sort by id then by month_int
    df['id_shift_1'] = df['id'].shift(1).fillna(0).astype(np.int32)

    idx_to_remove = ((df['id'] - df['id_shift_1']) != 0) #store index unwanted entries

    #add shifted target colums
    for col in target_products:
        name = col + '_s_1'
        df[name] = df[col].shift(1).fillna(0).astype(np.int8)
        df.loc[idx_to_remove, name] = 0 #set to 0 so that the difference works out

    # set 1 only for added products not for existing products
    for col in target_cols:
        df[col] = (df[col] - df[col + '_s_1']).astype(np.int8)
        df[col] = (df[col] > 0).astype(np.int8)

    df = df[idx_to_remove == False] #remove illogical results
    return df

